version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE:-true}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD:-admin}
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=${N8N_PORT:-5678}
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
      - WEBHOOK_URL=${WEBHOOK_URL:-http://localhost:5678/}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-America/Mexico_City}
    ports:
      - "${N8N_PORT:-5678}:5678"
    volumes:
      - n8n-data:/home/node/.n8n
    restart: unless-stopped
    networks:
      - n8n-network

  # PostgreSQL para N8N (opcional pero recomendado)
  n8n-postgres:
    image: postgres:16-alpine
    container_name: n8n-postgres
    environment:
      POSTGRES_USER: ${N8N_DB_USER:-n8n}
      POSTGRES_PASSWORD: ${N8N_DB_PASSWORD:-n8n}
      POSTGRES_DB: ${N8N_DB_NAME:-n8n}
    volumes:
      - n8n-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - n8n-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${N8N_DB_USER:-n8n}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  n8n-data:
  n8n-postgres-data:

networks:
  n8n-network:
    driver: bridge
