version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    restart: unless-stopped
    networks:
      - ollama-network

  # Open WebUI para interactuar con Ollama
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    ports:
      - "${WEBUI_PORT:-3001}:8080"
    volumes:
      - open-webui-data:/app/backend/data
    restart: unless-stopped
    networks:
      - ollama-network
    depends_on:
      - ollama

volumes:
  ollama-data:
  open-webui-data:

networks:
  ollama-network:
    driver: bridge
