version: '3.8'

services:
  nextjs:
    image: node:18-alpine
    container_name: nextjs-app
    working_dir: /app
    volumes:
      - ./app:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: sh -c "npm install && npm run build && npm start"
    restart: unless-stopped
    networks:
      - nextjs-network

networks:
  nextjs-network:
    driver: bridge
